//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenMedStack.NEventStore.Abstractions {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("OpenMedStack.NEventStore.Abstractions.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AppendingUncommittedToStream {
            get {
                return ResourceManager.GetString("AppendingUncommittedToStream", resourceCulture);
            }
        }
        
        internal static string AttemptingToCommitChanges {
            get {
                return ResourceManager.GetString("AttemptingToCommitChanges", resourceCulture);
            }
        }
        
        internal static string UnderlyingStreamHasChanged {
            get {
                return ResourceManager.GetString("UnderlyingStreamHasChanged", resourceCulture);
            }
        }
        
        internal static string ClearingUncommittedChanges {
            get {
                return ResourceManager.GetString("ClearingUncommittedChanges", resourceCulture);
            }
        }
        
        internal static string AddingCommitsToStream {
            get {
                return ResourceManager.GetString("AddingCommitsToStream", resourceCulture);
            }
        }
        
        internal static string IgnoringBeyondRevision {
            get {
                return ResourceManager.GetString("IgnoringBeyondRevision", resourceCulture);
            }
        }
        
        internal static string IgnoringBeforeRevision {
            get {
                return ResourceManager.GetString("IgnoringBeforeRevision", resourceCulture);
            }
        }
        
        internal static string AlreadyDisposed {
            get {
                return ResourceManager.GetString("AlreadyDisposed", resourceCulture);
            }
        }
        
        internal static string NoChangesToCommit {
            get {
                return ResourceManager.GetString("NoChangesToCommit", resourceCulture);
            }
        }
        
        internal static string PersistingCommit {
            get {
                return ResourceManager.GetString("PersistingCommit", resourceCulture);
            }
        }
        
        internal static string BuildingCommitAttempt {
            get {
                return ResourceManager.GetString("BuildingCommitAttempt", resourceCulture);
            }
        }
        
        internal static string StreamNotFoundException {
            get {
                return ResourceManager.GetString("StreamNotFoundException", resourceCulture);
            }
        }
        
        internal static string DuplicateCommitIdException {
            get {
                return ResourceManager.GetString("DuplicateCommitIdException", resourceCulture);
            }
        }
    }
}
